### ISSUE TITLE
"Data may not be available" error

### ISSUE THREAD

**Issue by lnicoletti** [worldbank/blackmarblepy#17]
Hello,

I followed the exact steps from the documentation/README but running `bm_raster` or `bm_extract` always returns the following error:

`Skipping XXX-XX-XX due to error. Data may not be available.`

**Comment by g4brielvs** [comment]
@lnicoletti Thanks **so** much opening this issue. This package is currently a pre-release and we'll address https://github.com/worldbank/blackmarblepy/issues/16 shortly. Please bear with us and stay tuned.

**Comment by g4brielvs** [comment]
@lnicoletti  Happy to say [v0.2.0 is now on PyPI](https://pypi.org/project/blackmarblepy/). We've also prepared a few examples on the [documentation](https://worldbank.github.io/blackmarblepy/examples/blackmarblepy.html). Please let us know if you run into any issues or if you have any feedback.
