### ISSUE TITLE
Issue loading package / calling function

### ISSUE THREAD

**Issue by ramarty** [worldbank/blackmarblepy#29]
I'm getting an error loading the package / calling the function.

See error loading package
![Screen Shot 2023-12-07 at 10 31 54 AM](https://github.com/worldbank/blackmarblepy/assets/11593422/04bba9f1-8b0a-4a24-a66d-ffa558d3a8ba)

This worked:
```
from blackmarble import bm_extract
from blackmarble import bm_raster
```

But then I get this error calling the function

![load_raster](https://github.com/worldbank/blackmarblepy/assets/11593422/c24bd0e2-cb8a-41ff-8a13-c51995c7d35a)

I installed the lastest version from pip, and am using python 3.11.5

**Comment by g4brielvs** [comment]
@ramarty Apologies for that! The [v0.2.0](https://github.com/worldbank/blackmarblepy/milestone/1) hasn't been published to PyPI yet (but it will today!). If you'd like to try immediately, could you please try installing from the repository instead:

```
pip install git+https://github.com/worldbank.com/blackmarblepy
```

**Comment by g4brielvs** [comment]
@ramarty Happy to say [v0.2.0 is now on PyPI](https://pypi.org/project/blackmarblepy/). Please let me know if you run into any issues and thanks a lot again for working together on this!
