### ISSUE TITLE
Issue with `quality_flag_rm`

### ISSUE THREAD

**Issue by ramarty** [worldbank/blackmarblepy#31]
It seems there's an issue with removing cells based on quality.

For example, this:

```
ntl_r = bm_raster(
    gdf,
    product_id="VNP46A2",
    date_range="2023-01-01",
    bearer=bearer,
    variable="DNB_BRDF-Corrected_NTL",
    quality_flag_rm=[2, 255],
)

fig, ax = plt.subplots()

# Plot
ntl_r["DNB_BRDF-Corrected_NTL"].sel(time="2023-01-01").plot(
    ax=ax, cmap=cc.cm.bmy, robust=True
)
cx.add_basemap(ax, crs=gdf.crs.to_string(), source=cx.providers.CartoDB.Positron)

plt.axis("off")
plt.tight_layout()
```

displays this:

![Screen Shot 2023-12-07 at 11 11 56 AM](https://github.com/worldbank/blackmarblepy/assets/11593422/02bbf085-358b-4fe3-8e28-b1d2cfabff9e)

But when removing "0" as well, it looks the same -- when most of these pixels are good quality (0), so these should be removed / set to na as well.

```
ntl_r = bm_raster(
    gdf,
    product_id="VNP46A2",
    date_range="2023-01-01",
    bearer=bearer,
    variable="DNB_BRDF-Corrected_NTL",
    quality_flag_rm=[0, 2, 255],
) 
```

Same plotting code as above, and figure looks the same.

@g4brielvs I'll take a look here, but not sure if you have any quick thoughts?

**Comment by g4brielvs** [comment]
@ramarty Thanks for reporting this issue! Yes... The argument is not being passed to [h5_to_geotiff](https://github.com/worldbank/blackmarblepy/blob/4d57dedbac1087b98ce8b0eebfe380564e83e190/src/blackmarble/raster.py#L284).
