### ISSUE TITLE
Fix skip if exists

### ISSUE THREAD

**Issue by g4brielvs** [worldbank/blackmarblepy#38]
The `file_skip_if_exists` was removed and needs to be reimplemented.

**Comment by ArieClaassens** [comment]
Thanks for the great work, but files are repeatedly downloaded, even if the ile_skip_if_exists=True parameter is passed in the sample code with the bm_raster function.. Inspection of the download.py module doesn't show any logic to check for existing local files.

**Comment by ArieClaassens** [comment]
Thank you!
