### ISSUE TITLE
Title name in the documentation ("blackmarble package")

### ISSUE THREAD

**Issue by yukinko-iwasaki** [worldbank/blackmarblepy#39]
**Is your feature request related to a problem? Please describe.**

It took me some time to notice that the API interface is under "blackmarble package.
<img src=https://github.com/worldbank/blackmarblepy/assets/18432543/21177993-37bd-4ec0-958e-f13bd8c4825f width="300" height="500">
**Describe the solution you'd like**
It might be more intuitive if it was named something like "API Interface" 

**Describe alternatives you've considered**
"Reference"

**Additional context**
N/A

**Comment by g4brielvs** [comment]
@yukinko-iwasaki Thanks for contributing! We'll make the change.
