### ISSUE TITLE
Issues when downloading many files

### ISSUE THREAD

**Issue by ramarty** [worldbank/blackmarblepy#40]
I was downloading data for multiple days and the "retrieving" failed a few times. The function still worked, as it's designed to retry. But not sure if there's something going on where it's trying to download too much at one time? Not sure if limiting to, say, 2-3 concurrent downloads would help this issue? (I never seem to get these red bars when downloading just a couple tiles at once).

![Screen Shot 2023-12-20 at 6 43 16 PM](https://github.com/worldbank/blackmarblepy/assets/11593422/f50f57d1-ed9f-489b-afa5-ed990afda3d4)

**Comment by ramarty** [comment]
My internet was really bad when this happened - when I switched to better internet it didn't happen! But maybe still something to think about?

**Comment by Holly-Transport** [comment]
I also encountered many instances of file download timing out.

**Comment by g4brielvs** [comment]
> I was downloading data for multiple days and the "retrieving" failed a few times. The function still worked, as it's designed to retry. But not sure if there's something going on where it's trying to download too much at one time? Not sure if limiting to, say, 2-3 concurrent downloads would help this issue? 

@ramarty Thanks (and happy new year)! That's something to consider. There seems to be 2 things at play. The number of parallel downloads may be too ambitious. In the next release, we can change the default and expose the parameter for the user to choose. In the other hand, especially in slower connections, the default `httpx.Client` may be timing out too soon. This issue would persist even if we decreased the number of parallel downloads. We can increase the `timeout` (or even set it to never time out).
