### ISSUE TITLE
Geopandas package installation

### ISSUE THREAD

**Issue by Holly-Transport** [worldbank/blackmarblepy#42]
In the example notebook, when installing geopandas, pip automatically installed 0.9.0, but it seems version (at least) 0.10.2 is required for .explore() to work. May consider as a comment or in the !pip install code the minimum version requirements for geopandas.

**Comment by g4brielvs** [comment]
> In the example notebook, when installing geopandas, pip automatically installed 0.9.0, but it seems version (at least) 0.10.2 is required for .explore() to work. May consider as a comment or in the !pip install code the minimum version requirements for geopandas.

@Holly-Transport Thanks!
