### ISSUE TITLE
Broken NASA link

### ISSUE THREAD

**Issue by kbjarkefur** [worldbank/blackmarblepy#48]
The `https://ladsweb.modaps.eosdis.nasa.gov/archive/allData/5000/VNP46A3` link in:

https://github.com/worldbank/blackmarblepy/blob/5a4c0403b9fa585599094a7fe3e157345b161b30/README.md?plain=1#L35

Gives me this page with a 500 error. Is that a temporary error? Or is it something I am doing wrong?

![image](https://github.com/worldbank/blackmarblepy/assets/15911801/f0a9229d-bef3-459f-b5fc-93e3dee9fe29)

**Comment by ramarty** [comment]
@kbjarkefur This seems to be temporary - when I click __Data Archive__ from here, I get the above error: 

https://ladsweb.modaps.eosdis.nasa.gov/missions-and-measurements/products/VNP46A3/

**Comment by ramarty** [comment]
@g4brielvs Maybe we can add in readme that their website may occasionally go down -- this has happened to me before (and maybe more reason to switch to querying from AWS)

**Comment by g4brielvs** [comment]
> @g4brielvs Maybe we can add in readme that their website may occasionally go down -- this has happened to me before (and maybe more reason to switch to querying from AWS)

Oh NASA...adding a note to the docs makes sense. Also, Earthdath is updating the password rotation requirements, which could mean other changes may be underway.
