### ISSUE TITLE
[Documentation] Add information on building documentation and running tests locally

### ISSUE THREAD

**Issue by elbeejay** [worldbank/blackmarblepy#52]
It'd be great if the documentation included "instructions for developers" on things like:

- Setting up a "developer" environment with an editable installation of the package
- Building the documentation locally
- Running the tests and calculating the code coverage locally

<br>

Current guidance on the [contributing page](https://worldbank.github.io/blackmarblepy/CONTRIBUTING.html) does a good job covering how contributions should be made. It is unfortunate that the hyperlink in the readme ([this](https://github.com/worldbank/blackmarblepy/blob/main/CONTRIBUTING.md)) does not work, but since it works in the hosted documentation I'm wondering if changing it in the readme would break that link...

**Comment by g4brielvs** [comment]
@elbeejay Thanks! Excepts for tests, #53 should address these items.
