### ISSUE TITLE
OSError: Unable to synchronously open file (file signature not found)

### ISSUE THREAD

**Issue by dpatil-fw** [worldbank/blackmarblepy#55]
**Describe the bug**
OSError: Unable to synchronously open file (file signature not found)

**To Reproduce**
Just running a simple bm_raster call from the examples is giving this error:

GETTING MANIFEST...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:03<00:00,  1.10it/s]
QUEUEING TASKS | Downloading...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 360/360 [00:00<00:00, 2926.85it/s]
PROCESSING TASKS | Downloading...:  75%|█████████████████████████████████████████[2024-02-10 22:28:56 - backoff:105 - INFO] Backing off _download_file(...) for 0.0s (httpx.ConnectTimeout: timed out)
PROCESSING TASKS | Downloading...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 360/360 [00:30<00:00, 11.77it/s]
COLLECTING RESULTS | Downloading...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 360/360 [00:00<?, ?it/s]
COLLATING RESULTS | Processing...:   0%|                                                                                                            | 0/90 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\pythonTest\blackMarble.py", line 37, in <module>
    daily = bm_raster(
  File "C:\Users\Python310\lib\site-packages\pydantic\validate_call_decorator.py", line 58, in wrapper_function
    return validate_call_wrapper(*args, **kwargs)
  File "C:\Users\Python310\lib\site-packages\pydantic\_internal\_validate_call.py", line 81, in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
  File "C:\Users\Python310\lib\site-packages\blackmarble\raster.py", line 283, in bm_raster
    da = [
  File "C:\Users\Python310\lib\site-packages\blackmarble\raster.py", line 285, in <listcomp>
    h5_to_geotiff(
  File "C:\Users\Python310\lib\site-packages\blackmarble\raster.py", line 66, in h5_to_geotiff
    with h5py.File(f, "r") as h5_data:
  File "C:\Users\Python310\lib\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "C:\Users\Python310\lib\site-packages\h5py\_hl\files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)

Any help is appreciated

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by g4brielvs** [comment]
@dpatil-fw Thank you **so** much for reporting this issue. It seems that the package is failing to read the downloaded HDF5 file. I'll have to investigate further.

**Comment by Chatrasham** [comment]
I am facing this issue as well. I followed the steps in the documentation and faced the same error reported here.

**Comment by cygniv404** [comment]
Any updates on this ?

**Comment by mashafif** [comment]
Hi! I was facing the same issue as well.

But when I tried to download the blackmarble HDF5  file manually from this website:
[NASA blackmarble manual download](https://ladsweb.modaps.eosdis.nasa.gov/search/order/2/VNP46A3--5000)

It prompts me to fill out my "Affiliation" information on my [Earthdata](https://urs.earthdata.nasa.gov/profile/edit) login profile.

![Earthdata_Required_Profile](https://github.com/user-attachments/assets/bbd54d94-3aeb-4dd0-bf18-d15dfdedcf00)

After filling out the required affiliation information, now I can download the HDF5 properly, and this error has disappeared. 

It seems our TOKEN to access the API will not be valid, unless if we fill out the required "Affiliation"  information on our Earthdata profile. 

I hope it helps!

**Comment by g4brielvs** [comment]
@mashafif Thank you **so** much for your contribution! @aizadyar23 @cygniv404 Could you please check if the "Affiliation" might be missing and confirm if filling it out solves the issue?

**Comment by lAleksandrl** [comment]
Hi there! Unfortunately I have this problem despite having filled out the affiliate form. Any suggestions? 
![Screenshot 2024-12-11 at 09 46 55](https://github.com/user-attachments/assets/e7ea0a9a-2b6b-41b5-afb3-a9088feea44e)
