### ISSUE TITLE
NTL on specific city or municipality

### ISSUE THREAD

**Issue by brissyaussieoleh** [worldbank/blackmarblepy#66]
Hello, I would like to ask for help regarding my research. I already have the visualization of the NTL radiance of a specific city or municipality but I was not satisfied with the results because the map is zoomed in and the NTL radiance is pixelated. What is the proper solution for this one? Thank you.

**Comment by g4brielvs** [comment]
@brissyaussieoleh Thanks for contributing. Based on the information you've shared, please note that the [NASA Black Marble](https://blackmarble.gsfc.nasa.gov/)'s spatial resoltion is of `15 arc second` or roughly ~`500m` in the Equator. When looking at a city-level, you may see the a pixelated image indeed as this related to the upstream data provided by NASA.

**Comment by g4brielvs** [comment]
@brissyaussieoleh I would like to check in. Have you been able to use NTL in your research?

**Comment by brissyaussieoleh** [comment]
Yes, and I need to review the results because I haven't finished my thesis for this one yet.
