### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by Rasanka1991** [worldbank/blackmarblepy#67]
It seems that the documentation file is currently unavailable due to a broken link: [https://worldbank.github.io/blackmarblepy/examples/blackmarblepy.html](https://worldbank.github.io/blackmarblepy/examples/blackmarblepy.html). Is there an alternative link or another source where I might find the documentation?

**Comment by g4brielvs** [comment]
@Rasanka1991 Thank you for reporting this issue. The content is now available at [this page](https://worldbank.github.io/blackmarblepy/notebooks/blackmarblepy.html#). Could you please point me to where you found the broken link?

**Comment by iled** [comment]
The broken link is in the [readme](https://github.com/worldbank/blackmarblepy?tab=readme-ov-file#usage), where it says: 

> For more detailed information and examples, please refer to the [documentation](https://worldbank.github.io/blackmarblepy/examples/blackmarblepy.html).
