### ISSUE TITLE
Minor documentation issue in `blackmarble.raster.bm_raster`

### ISSUE THREAD

**Issue by shreyasgm** [worldbank/blackmarblepy#71]
### Description

`blackmarble.raster.bm_raster` takes parameter `gdf`, but the API reference mentions `roi` instead.

#### Screenshots / Error Messages (if applicable)

![image](https://github.com/worldbank/blackmarblepy/assets/10867686/c3ce1a0e-43a7-4295-ae34-c96528dca2fa)

**Comment by g4brielvs** [comment]
@shreyasgm Thank you for your contribution! I'll revise the documentation shortly.

**Comment by g4brielvs** [comment]
@all-contributors please add @shreyasgm for documentation
